name: "Continuous Deployment"
on:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Create Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ingsis-group-6
          password: ${{ secrets.TOKEN }}

      - name: Build and Push Docker image
        id: docker_build
        env:
          GITHUB_USERNAME: ${{ secrets.PUBLISH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: |
          docker build \
            --build-arg GITHUB_USERNAME=${GITHUB_USERNAME} \
            --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} \
            --tag ghcr.io/ingsis-group-6/snippet-manager:latest .
            
          docker push ghcr.io/ingsis-group-6/snippet-manager:latest
